name: dictionary_generator
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  google_generative_ai: ^0.4.7
  equatable: ^2.0.8
  #appwrite: ^13.0.0
  googleapis: ^15.0.0
  googleapis_auth: ^2.0.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  dart_appwrite: 16.0.0 #^20.1.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.6
